name: .NET

on:
  push:
    branches: [ unstable ]
  pull_request:
    branches: [ unstable ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.x'
    - name: Install dependencies
      run: dotnet restore src/ModularDoc.sln
    - name: Build
      run: dotnet build src/ModularDoc.sln --configuration Release --no-restore

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.x'
    - name: Install dependencies
      run: dotnet restore src/ModularDoc.sln && dotnet restore tests/ModularDoc.Tests.sln
    - name: Build project
      run: dotnet build src/ModularDoc.sln --configuration Debug --no-restore
    - name: Build tests
      run: dotnet build tests/ModularDoc.Tests.sln --configuration Debug --no-restore
    - name: Install tooling for conversion
      run: dotnet tool install -g trx2junit
    - name: Run tests
      run: dotnet test src/ModularDoc.sln --logger "trx"
    - name: Extract test results
      run: |
        mkdir artifacts
        for f in `find . -name '*.trx' -type f`; do mv $f artifacts; done
        trx2junit artifacts/*.trx
        rm -f artifacts/*.trx
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@v1.36
      if: always()
      with:
        files: "artifacts/*.xml"
        job_summary: true
