name: .NET

on:
  push:
    branches: [ unstable ]
  pull_request:
    branches: [ unstable ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.8.0
    - name: Install dependencies
      run: dotnet restore src/MarkDoc.sln
    - name: Build
      run: dotnet build src/MarkDoc.sln --configuration Release --no-restore

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.8.0
    - name: Install dependencies
      run: dotnet restore src/MarkDoc.sln && dotnet restore tests/MarkDoc.Tests.sln
    - name: Build project
      run: dotnet build src/MarkDoc.sln --configuration Debug --no-restore
    - name: Build tests
      run: dotnet build tests/MarkDoc.Tests.sln --configuration Debug --no-restore
    - name: Run tests
      run: dotnet test src/MarkDoc.sln --collect:"XPlat Code Coverage"
    - name: Upload coverage
      if: always()
      uses: codecov/codecov-action@v1
      with:
        file: "src/Tests/*/TestResults/*/*.xml"
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false
